
spring:

  data:
    mongodb:
      host: localhost
      auto-index-creation: true
      database: mydb
server:
  port: 8081


springbootwebfluxjjwt:
  jjwt:
    secret: XwO5hbRdHYDY63LfdzxdbaXLXiA8/flrcz2ni15Qq2sHGgbxc/Vi+2ULCEaXUDL3kzCyAWWKl1mArKOBfRR1vcBFfSlZ7nNpeyb1FaJapkBCh1lHImlTcpK03kCahRAFfBw25TD2jbbUoxNEtI/xppvjMe/GNw23tJy17wZFuH4=
    expiration: 10
  password:
    encoder:
      secret: CHANGE_ME_ENCODER_ABCDEFGHIJKLMNOP
      iteration: 33
      keylength: 256
logging:
  level:
    org.springframework.security: trace